### ISSUE TITLE
Dataset update request for experimental result 

### ISSUE THREAD

**Issue by JmeiLiu** [awarelab/continual_world#7]
The link to the experimental result dateset is broken, can it be updated?

**Comment by lanyily** [comment]
@Fafa-forever I downloaded the experimental data before, see [the link](https://github.com/lanyily/Backup-of-Continual-World-experiment-records./tree/master)

**Comment by lanyily** [comment]
> The link to the experimental result dateset is broken, can it be updated?

by the way, have you encountered [this problem](https://github.com/awarelab/continual_world/issues/8) before?

**Comment by michalzajac-ml** [comment]
Thank you for raising this issue. I have updated the link in the readme.
